def failing_function():
    assert(False)

___assertRaises(AssertionError, failing_function)
